/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiWebhooksChannelRouteImport } from './routes/api/webhooks.$channel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksChannelRoute = ApiWebhooksChannelRouteImport.update({
  id: '/api/webhooks/$channel',
  path: '/api/webhooks/$channel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/documents': typeof DocumentsRoute
  '/mcp': typeof McpRoute
  '/playbooks': typeof PlaybooksRoute
  '/queues': typeof QueuesRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/webhooks/$channel': typeof ApiWebhooksChannelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/documents': typeof DocumentsRoute
  '/mcp': typeof McpRoute
  '/playbooks': typeof PlaybooksRoute
  '/queues': typeof QueuesRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/webhooks/$channel': typeof ApiWebhooksChannelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/documents': typeof DocumentsRoute
  '/mcp': typeof McpRoute
  '/playbooks': typeof PlaybooksRoute
  '/queues': typeof QueuesRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/webhooks/$channel': typeof ApiWebhooksChannelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/documents'
    | '/mcp'
    | '/playbooks'
    | '/queues'
    | '/api/mcp'
    | '/api/webhooks/$channel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/documents'
    | '/mcp'
    | '/playbooks'
    | '/queues'
    | '/api/mcp'
    | '/api/webhooks/$channel'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/documents'
    | '/mcp'
    | '/playbooks'
    | '/queues'
    | '/api/mcp'
    | '/api/webhooks/$channel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  DocumentsRoute: typeof DocumentsRoute
  McpRoute: typeof McpRoute
  PlaybooksRoute: typeof PlaybooksRoute
  QueuesRoute: typeof QueuesRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiWebhooksChannelRoute: typeof ApiWebhooksChannelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/$channel': {
      id: '/api/webhooks/$channel'
      path: '/api/webhooks/$channel'
      fullPath: '/api/webhooks/$channel'
      preLoaderRoute: typeof ApiWebhooksChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  DocumentsRoute: DocumentsRoute,
  McpRoute: McpRoute,
  PlaybooksRoute: PlaybooksRoute,
  QueuesRoute: QueuesRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiWebhooksChannelRoute: ApiWebhooksChannelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
